version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name kadai_20240220 --s3-location s3://kadai-20240220/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src